// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TimKotowski/pg_elector/driver (interfaces: Driver,Querier)
//
// Generated by this command:
//
//	mockgen -destination=driver/mockDriver/mock_driver.go -package=mockDriver github.com/TimKotowski/pg_elector/driver Driver,Querier
//

// Package mockDriver is a generated GoMock package.
package mockDriver

import (
	context "context"
	reflect "reflect"

	driver "github.com/TimKotowski/pg_elector/driver"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// GetQuerier mocks base method.
func (m *MockDriver) GetQuerier() driver.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuerier")
	ret0, _ := ret[0].(driver.Querier)
	return ret0
}

// GetQuerier indicates an expected call of GetQuerier.
func (mr *MockDriverMockRecorder) GetQuerier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuerier", reflect.TypeOf((*MockDriver)(nil).GetQuerier))
}

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AcquireLeadership mocks base method.
func (m *MockQuerier) AcquireLeadership(ctx context.Context, param driver.AcquireLeadershipParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireLeadership", ctx, param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireLeadership indicates an expected call of AcquireLeadership.
func (mr *MockQuerierMockRecorder) AcquireLeadership(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireLeadership", reflect.TypeOf((*MockQuerier)(nil).AcquireLeadership), ctx, param)
}

// LeaderRenewal mocks base method.
func (m *MockQuerier) LeaderRenewal(ctx context.Context, param driver.LeaderRenewalParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaderRenewal", ctx, param)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaderRenewal indicates an expected call of LeaderRenewal.
func (mr *MockQuerierMockRecorder) LeaderRenewal(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaderRenewal", reflect.TypeOf((*MockQuerier)(nil).LeaderRenewal), ctx, param)
}
