// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Leaders struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	RenewedAt pgtype.Timestamptz
	Term      int64
	Name      string
	LeaderID  string
}
