// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"
)

type Leaders struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	RenewedAt time.Time
	Term      int64
	Name      string
	LeaderID  string
}
