// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbsqlc

import (
	"context"
)

const acquireLeadership = `-- name: AcquireLeadership :execrows
INSERT INTO leaders(name, leader_id, elected_at, expires_at)
VALUES($1, $2, now(), MAKE_INTERVAL(secs => $3)) ON CONFLICT (name) DO UPDATE
SET elected_at = NOW(),
    expires_at = NOW() + MAKE_INTERVAL(secs => $3),
    renewed_at = NULL,
    term = leaders.term + 1,
    leader_id = $2
WHERE expires_at < NOW() AND name = $1
`

type AcquireLeadershipParams struct {
	Name          string
	Leaderid      string
	Leaseduration float64
}

func (q *Queries) AcquireLeadership(ctx context.Context, db DBTX, arg *AcquireLeadershipParams) (int64, error) {
	result, err := db.ExecContext(ctx, acquireLeadership, arg.Name, arg.Leaderid, arg.Leaseduration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const leaderRenewal = `-- name: LeaderRenewal :execrows
UPDATE leaders
SET renewed_at = NOW(),
    expires_at = NOW() + MAKE_INTERVAL(secs => $1)
WHERE name = $2 AND leader_id = $3
`

type LeaderRenewalParams struct {
	Leaseduration float64
	Name          string
	Leaderid      string
}

func (q *Queries) LeaderRenewal(ctx context.Context, db DBTX, arg *LeaderRenewalParams) (int64, error) {
	result, err := db.ExecContext(ctx, leaderRenewal, arg.Leaseduration, arg.Name, arg.Leaderid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseLeadership = `-- name: ReleaseLeadership :exec
DELETE FROM leaders
WHERE name = $1 AND leader_id = $2
`

type ReleaseLeadershipParams struct {
	Name     string
	Leaderid string
}

func (q *Queries) ReleaseLeadership(ctx context.Context, db DBTX, arg *ReleaseLeadershipParams) error {
	_, err := db.ExecContext(ctx, releaseLeadership, arg.Name, arg.Leaderid)
	return err
}
